blog/urls.py
from django.urls import path 
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('shortmort', views.shortmort, name='shortmort'),
    path('stories', views.stories, name='stories'),
]

gallery/urls.py
from django.urls import path 
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.gallery, name='gallery'),
    path('<int:gallery_id>/', views.details, name='details'),
]

pb/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class  Blog(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(max_length=200)
    date = models.DateField()

    
    def __str__(self):
        return self.title

gallery/models.py
from django.db import models

class  Gallery(models.Model):
    title = models.CharField(max_length=30, blank=True)
    description = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to='gallery/images')
    
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date') [:3]
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

def shortmort(request): 
    return render(request, 'blog/shortmort.html',{'shortmort':shortmort})

def stories(request): 
    return render(request, 'blog/stories.html',{'stories':stories})

gallery/views.py
from django.shortcuts import render, get_object_or_404
from .models import Gallery

def gallery(request): 
    galleries = Gallery.objects.all()
    return render(request, 'gallery/gallery.html', {'galleries': galleries})

def details(request, gallery_id):
    gallery = get_object_or_404(Gallery, pk=gallery_id)
    return render(request, 'gallery/details.html',{'gallery':gallery})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html ' %}

{% load static %}

{% block content %}

<h1>Hello Blog</h1>

<h2>Number of written is {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

blog/templates/blog/shortmort.html
{% extends 'portfolio/base.html ' %}
{% block content %}

<h1>Shortmort</h1>



{% endblock %}

blog/templates/blog/stories.html
{% extends 'portfolio/base.html ' %}
{% block content %}

<h1>Stories</h1>
    {% load static %}
    <img src="{% static 'portfolio/5aab895s.jpg' %}" height=600>


{% endblock %}

gallery/templates/gallery/details.html
{% extends 'portfolio/base.html ' %}

{% block content %}

<img src="{{ gallery.image.url }}" height=200></br>

<h1>{{ gallery.title }} </h1>

{{ gallery.description }}<br>

<a href="{% url 'gallery:gallery' %}">back</a>

{% endblock %}

gallery/templates/gallery/gallery.html
{% extends 'portfolio/base.html ' %}
{% block content %}

    <h1>Gallery</h1>



    <div class="container">
    <h2 class="mt-5">Gallery</h2>
    <hr>
    <div class="row">
    {% for gallery in galleries %}
    <div class="col-lg-4 col-md-6">

      
        <a href="{% url 'gallery:details' gallery.id %}"><h1>{{ gallery.title }}</h1></a>

        <img src="{{ gallery.image.url }}" class="img-fluid mb-2">
        
        <h3>{{ gallery.title }}</h3>
        <p>{{ gallery.description|truncatechars:80  }}</p>

    </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

portfolio/templates/portfolio/about.html
<h1>About page site</h1>

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:shortmort' %}">Shortmort <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
            </li>            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:stories' %}">Stories</a>
            </li>            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
            </li>            
            </ul>            
        </div>
    </nav>


{% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/5aab895s.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Nick Walter is Commander-in-Chief at ZappyCode and lives in Downtown Tokyo 😊</h1>
  </div>
</div>
<div class="container">
    <h2 class="mt-5">Portfolio</h2>
    <hr>
    <div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href="{{ project.url }}">
        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}

        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}